apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mlops-deployment
spec: 
  replicas: 3
  selector: 
    matchLabels:
      app: mlops
  template:
    metadata:
      labels:
        app: mlops
    spec:
      containers:
      - name: mlops
        image: mlops:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000


